### PR TITLE
videojs-controls, based on user selection

### PR DESCRIPTION
**Pull request by afraz-malik**
- Allowing users to set the **controls** of web player.

### CODE REVIEW

**Comment by bazookanu** [comment]
@mustafaboleken @lastpeony we are ant media users and would like to have this option. could you please review this PR?

**Comment by mustafaboleken** [comment]
Hi @bazookanu  and @afraz-malik 

Thanks for the pull request, I will review and merge it.

**Comment by mustafaboleken** [comment]
I tested and it works. I have 1 comment, please update the comment section of the controls with 

```
/**
 * controls: Toggles the visibility of player controls.
*/

```
then, I will merge it.

**Comment by bazookanu** [comment]
@mustafaboleken done!

**Review by mustafaboleken — APPROVED** [review]
lgtm

**Comment by mustafaboleken** [comment]
Thanks again for the pull request. You can use the latest snapshot version. with 

<br class="Apple-interchange-newline">[2.12.0-SNAPSHOT-2024-Oct-31-06-24](https://www.npmjs.com/package/@antmedia/web_player/v/2.12.0-SNAPSHOT-2024-Oct-31-06-24)

**Pull request merged**
